### ISSUE TITLE
GDL Bot Added/ Removed Commands Log

### ISSUE THREAD

**Issue by VulcanGDL** [GDLDiscord/GDLBot#19]
Any commands that get re added will be posted to this issue page! (comment section)

**Comment by VulcanGDL** [comment]
+music
+rndstatus (owner only)
+admin (owner only)
+away

**Comment by VulcanGDL** [comment]
+logger (server admins)

**Comment by VulcanGDL** [comment]
+punish (server mods only)

**Comment by VulcanGDL** [comment]
+you're favorite lmao command 😉

**Comment by VulcanGDL** [comment]
+roller

**Comment by VulcanGDL** [comment]
+welcome
+onjoin
+lottery

**Comment by VulcanGDL** [comment]
+account

**Comment by VulcanGDL** [comment]
+customgcom (owner only)

**Comment by VulcanGDL** [comment]
+youtube

**Comment by VulcanGDL** [comment]
+pingt

**Comment by VulcanGDL** [comment]
+pressf

**Comment by VulcanGDL** [comment]
+avatar

**Comment by VulcanGDL** [comment]
+coupon

Create coupons for credits too be redeemed by you're members:

DO:

gdl-coupon create <no of credits> 

The bot will DM the coupon creator with the code, create can then send the code to the user who then needs to do:

gdl-coupon redeem <coupon code>

Enjoy :wink:

**Comment by VulcanGDL** [comment]
+strawpoll

**Comment by VulcanGDL** [comment]
+massdm (server owner)

**Comment by VulcanGDL** [comment]
+steam

**Comment by VulcanGDL** [comment]
+hackban (moderators with ban perms)

Ban members from there ID (They dont have to be in the server)

**Comment by VulcanGDL** [comment]
+insult

**Comment by VulcanGDL** [comment]
+massmove

Mass move members from one voice channel to another!

`gdl-massmove <from channel> <to channel>` - Must use channel ID's

so

`gdl-massmove 294872676869079040 245675782662389761

**Comment by VulcanGDL** [comment]
+catfacts

Do you like cats? 🐱 We'll your in luck!

Do - `gdl-catfact` to get a random fact about cats!

**Comment by VulcanGDL** [comment]
+duel

Duel a user = `gdl-duel @user#0000`

If you attempt to duel the bot you will just get trolled 😉

**Comment by VulcanGDL** [comment]
+20questions

`gdl-twentyq` 

Twenty Questions ¯\_(ツ)_/¯

**Comment by VulcanGDL** [comment]
+yomamma

`gdl-yomamma @user#0000` 

Insult a user with a yomamma joke

**Comment by VulcanGDL** [comment]
+welcomer

Advanced welcome messages

`gdl-welcomer` to get setup

**Comment by VulcanGDL** [comment]
+trigger

**Comment by VulcanGDL** [comment]
+invite
+sever
+support

All these commands are under the Advanced_bot_help although this is set to change for easier understanding and future writing!

`gdl-invite` - get a link for the bot
`gdl-server` get a link for the gdl server
`gdl-support` get a link for the support channel in the gdl server

**Comment by BangAndTheDirtIsGone** [comment]
*+server not +sever <3

**Comment by VulcanGDL** [comment]
+google 

Search for something on google - web or images 

ie: `gdl-google <search>
or
`gdl-google image <name of image>

Enjoy 👍

**Comment by VulcanGDL** [comment]
+volume 

How to volume guide: `gdl-volume`

**Comment by VulcanGDL** [comment]
+tts

`gdl-tts <what ever you want it too say>`

Users must be in a voice channel for this too work

**Comment by VulcanGDL** [comment]
+hunting

**Comment by VulcanGDL** [comment]
+buyrole
+seen
+sinfo
+customgcom
+news
+remindme

**Comment by VulcanGDL** [comment]
+antilink
+quote
+translated
+gaming
+oweather (key required)

**Comment by VulcanGDL** [comment]
+NSFW

**Comment by VulcanGDL** [comment]
+role

**Comment by VulcanGDL** [comment]
+ascii

**Comment by VulcanGDL** [comment]
+rift (needs slight edit)

**Comment by VulcanGDL** [comment]
+countrycode

**Comment by VulcanGDL** [comment]
Im going to close this, its kinda pointless lol
