### ISSUE TITLE
Anti Spam Bot

### ISSUE THREAD

**Issue by JWGDL** [GDLDiscord/GDLBot#3]
We need to add a bot for anti spam ~

When a user spams all there roles will be removed and given the punish role and then can use the punished members chat. - Much needed feature after looking around

**Comment by VulcanGDL** [comment]
Messaged Tom about Dixionary chutiye bot as that does the anti spam. Whether we can get it to work will be another story. It could be implemented into GDL Bot tho.

**Comment by VulcanGDL** [comment]
With the agree feature gone we don't need to worry about the bot removing the role and giving the punished role. As long as the bot gives the role when someone spams then it is all good.

**Comment by VulcanGDL** [comment]
Dyno now removes and auto mutes anyone who spams 👍

**Comment by VulcanGDL** [comment]
Due to the new server a anti spam feature needs re adding

**Comment by VulcanGDL** [comment]
This would now go under the server respitory
