### ISSUE TITLE
idea ¬⌣¬

### ISSUE THREAD

**Issue by ToxicDYSfunction** [GDLDiscord/GDLBot#66]
make the bot with a mini game like a shooter (which is pretty advanced) or a mini pac man game
also do like a duel system that's completely random with items used.

**Comment by Vulcannn** [comment]
pac man 0_o

**Comment by Vulcannn** [comment]
what do you mean by mini shooter game

**Comment by ToxicDYSfunction** [comment]
as in like a space invaders kinda bring classic games to gdl XD
# blkb;bjlk

**Comment by Vulcannn** [comment]
yeahno thats impossible xD
